version: "3.8"
services:
  zookeeper1:
    image: zookeeper
    restart: always
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - 12181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
  zookeeper2:
    image: zookeeper
    restart: always
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - 22181:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    depends_on:
      - zookeeper1
  zookeeper3:
    image: zookeeper
    restart: always
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - 32181:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    depends_on:
      - zookeeper1
  zoonavigator:
    image: elkozmon/zoonavigator
    container_name: zoonavigator
    restart: unless-stopped
    ports:
      - 9000:9000
    depends_on:
      - zookeeper1