version: "3.8"
services:
  cassandra1:
    image: cassandra
    restart: always
    hostname: cassandra1
    container_name: cassandra1
    ports:
      - 17000:7000
      - 19042:9042
    volumes:
      - /C/data/cassandra1/commitlog:/var/lib/cassandra/commitlog
      - /C/data/cassandra1/hints:/var/lib/cassandra/hints
      - /C/data/cassandra1/data:/var/lib/cassandra/data
      - /C/data/cassandra1/saved_caches:/var/lib/cassandra/saved_caches
      - /C/data/cassandra1/logs:/var/log/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cluster
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
  cassandra2:
    image: cassandra
    restart: always
    hostname: cassandra2
    container_name: cassandra2
    ports:
      - 27000:7000
      - 29042:9042
    volumes:
      - /C/data/cassandra2/commitlog:/var/lib/cassandra/commitlog
      - /C/data/cassandra2/hints:/var/lib/cassandra/hints
      - /C/data/cassandra2/data:/var/lib/cassandra/data
      - /C/data/cassandra2/saved_caches:/var/lib/cassandra/saved_caches
      - /C/data/cassandra2/logs:/var/log/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cluster
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
  cassandra3:
    image: cassandra
    restart: always
    hostname: cassandra3
    container_name: cassandra3
    ports:
      - 37000:7000
      - 39042:9042
    volumes:
      - /C/data/cassandra3/commitlog:/var/lib/cassandra/commitlog
      - /C/data/cassandra3/hints:/var/lib/cassandra/hints
      - /C/data/cassandra3/data:/var/lib/cassandra/data
      - /C/data/cassandra3/saved_caches:/var/lib/cassandra/saved_caches
      - /C/data/cassandra3/logs:/var/log/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cluster
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
  zookeeper1:
    image: zookeeper
    restart: always
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - 12181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
  zookeeper2:
    image: zookeeper
    restart: always
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - 22181:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
  zookeeper3:
    image: zookeeper
    restart: always
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - 32181:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
  zk-web:
    container_name: zk-web
    image: goodguide/zk-web
    ports:
      - 8080:8080