spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: localhost:12181, localhost:22181, localhost:32181
      discovery:
        root: /sayaya-document-classification/services
    gateway:
      routes:
        - id: model-service
          uri: lb://model-service
          filters:
            - StripPrefix=1
          predicates:
            - Path=/models/**
        - id: test-service
          uri: lb://test-service
          filters:
            - StripPrefix=1
          predicates:
            - Path=/test/**
server:
  port: 80