spring:
  application:
    name: model-service
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: localhost:22181
      discovery:
        root: /sayaya-document-classification/services
    stream:
      function:
        definition: publish-model;broadcast-model;publish-sample;broadcast-sample;analyze-sample
      bindings:
        publish-model-out-0.destination: models
        broadcast-model-in-0.destination: models
        publish-sample-out-0.destination: samples
        broadcast-sample-in-0.destination: samples
        analyze-sample-in-0:
          destination: samples
          group: analyze-samples
      kafka:
        binder:
          brokers: localhost
          auto-add-partitions: true
  data:
    cassandra:
      contact-points: localhost
      port: 19042
      keyspace-name: document_classification
      username: cassandra
      password: cassandra
      local-datacenter: dc1
      schema-action: CREATE_IF_NOT_EXISTS
server:
  port: 0