spring:
  application:
    name: model-service
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: localhost:22181
      discovery:
        root: /sayaya-document-classification/services
    stream:
      function:
        definition: publish;broadcast
        bindings:
          publish-out-0: models
          broadcast-in-0: models
      kafka:
        binder:
          brokers: localhost
  data:
    cassandra:
      contact-points: localhost
      port: 19042
      keyspace-name: document_classification
      username: cassandra
      password: cassandra
      local-datacenter: dc1
      schema-action: CREATE_IF_NOT_EXISTS
server:
  port: 0